-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 96fb7fa10f2f4c11ed33482a9ad7474251e5e97f
    hooks:
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: git://github.com/dnephin/pre-commit-golang
    sha: 9777e14eafc8fadf3429c66d2e0b7e85613bdc6e
    hooks:
    -   id: go-fmt
    -   id: go-vet
    -   id: go-lint
